# Generated by Django 2.0.3 on 2018-04-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('nazwa',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('nazwa',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nazwa',
        ),
    ]
