# Generated by Django 2.0.3 on 2018-04-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20180414_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('nazwa',), 'verbose_name': 'kategoria', 'verbose_name_plural': 'kategorie'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='utworzono',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='zaktalizowano',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cena',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='dopis',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='kategoria',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stan',
        ),
    ]
