# Generated by Django 2.0.3 on 2018-04-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20180414_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='produkty/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='shop_app.Category'),
        ),
    ]
