# Generated by Django 2.0.3 on 2018-04-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20180414_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produkt',
        ),
    ]
