# Generated by Django 2.0.3 on 2018-04-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20180414_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ('nazwa',), 'verbose_name': 'produkt', 'verbose_name_plural': 'produkty'},
        ),
    ]
