# Generated by Django 2.0.3 on 2018-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20180414_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='długość',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='materiał',
            field=models.CharField(db_index=True, default='brak', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='wysokość',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
