# Generated by Django 2.0.3 on 2018-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20180510_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='długość',
            field=models.DecimalField(decimal_places=0, default='0000000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='wysokość',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
