# Generated by Django 2.0.3 on 2018-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20180510_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='długość',
            field=models.DecimalField(decimal_places=0, default='0', editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='wysokość',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
