# Generated by Django 2.0.3 on 2018-05-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_auto_20180510_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='długość',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
