# Generated by Django 2.0.3 on 2018-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_auto_20180524_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='stan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
