# Generated by Django 2.0.3 on 2018-05-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_app', '0011_auto_20180524_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('zmieniono', models.DateTimeField(auto_now=True)),
                ('pay', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-utworzono',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop_app.Produkt')),
            ],
        ),
    ]
